### ISSUE TITLE
Run the whole ecosystem with a single command

### ISSUE THREAD

**Issue by gm50x** [BrunoBMelo/hebrom-fullstack-project#1]
Hey man!

Add a Dockerfile to that solution! This will allow you to add another service to your docker-compose.yml and run everything with a single docker-compose up command. By doing this, the build is orchestrated by the docker-compose process and therefore you are not only raising the database, but the whole ecosystem. The other advantage is that whoever is just trying to test your app, doesn't need to manually run anything, only this one command and everything is setup! 

An example of such configuration is the following: 
```
version: '3'
services:
  api-service:
    build:
      context: ./<path-to-dockerfile-directory>
    image: api-image-name
    depends_on:
      - db-container
    environment:
      PORT: 5001
    ports:
      - 5001:5001
    container_name: api-service
    networks:
      - skynet
  db-container:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd4postgres
    ports:
      - 5432:5432
    container_name: db-container
    networks:
      - skynet
networks:
  skynet:
    driver: bridge
```

Just keep in mind the the build in the docker-compose.yml needs to know the containing location of the Dockerfile and not its path.
